version: '3'

services:
  libra-db:
    image: postgres:10.4
    volumes:
      - libradb:/var/lib/postgresql/data/
  libra-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8004:8004"
    depends_on:
      - libra-db

volumes:
  libradb:
