version: '3'

services:
  libra_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
  libra_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8004:8004"
    depends_on:
      - libra_db
