version: '3'

services:
  libra_db:
    image: postgres:10.4
  libra_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8004:8004"
    depends_on:
      - libra_db
