# Generated by Django 2.0 on 2018-07-03 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('process_status', models.CharField(choices=[('queued', 'Report queued'), ('started', 'Report started'), ('completed', 'Report completed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FixityReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Report')),
            ],
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='FormatReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Report')),
            ],
            bases=('reports.report',),
        ),
    ]
